"""Write installer/version.iss from the single source of truth.

Keeps the installer version identical to app.__version__ — no
hand-maintained duplicate. Run before ISCC (build-installer.bat and CI
do this automatically):

    python installer/gen_version.py
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app import APP_MUTEX, __version__  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))


def main() -> None:
    out = os.path.join(HERE, "version.iss")
    with open(out, "w", encoding="utf-8") as f:
        f.write("; AUTO-GENERATED by gen_version.py — do not edit.\n")
        f.write(f'#define MyAppVersion "{__version__}"\n')
        f.write(f'#define MyAppMutex "{APP_MUTEX}"\n')
    print(f"wrote {out}: version {__version__}")


if __name__ == "__main__":
    main()
